# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 09:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100, unique=True)),
                ('Description', models.CharField(max_length=500)),
                ('Icon_Image', models.ImageField(upload_to='')),
                ('Background_Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('Post_Date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Idea', models.TextField(unique=True)),
                ('Tags', models.CharField(max_length=200)),
                ('Views', models.IntegerField(default=0)),
                ('Wants', models.IntegerField(default=0)),
                ('Shlts', models.IntegerField(default=0)),
                ('Post_Date', models.DateTimeField(default=datetime.datetime.now)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smw.Category')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smw.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('User', 'Text', 'Post')]),
        ),
    ]
