# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smw', '0002_extuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extuser',
            name='User',
        ),
        migrations.DeleteModel(
            name='extUser',
        ),
    ]
