# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smw', '0004_auto_20161115_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Background_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='Icon_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
