# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smw', '0005_auto_20161116_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
