from __future__ import unicode_literals

# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161109152719 on 2016-11-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smw', '0006_auto_20161118_0758'),
        ('smw', '0006_auto_20161118_1354'),
    ]

    operations = [
    ]
