# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smw', '0007_merge_20161122_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Shlts',
        ),
        migrations.AddField(
            model_name='post',
            name='Shlts',
            field=models.ManyToManyField(related_name='Shlts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='Wants',
        ),
        migrations.AddField(
            model_name='post',
            name='Wants',
            field=models.ManyToManyField(related_name='Wants', to=settings.AUTH_USER_MODEL),
        ),
    ]
